import Footer from "./components/Footer/Footer";
import Header from "./components/Header/Header";
import "./globals.css";

export const metadata = {
  title: "Adidas",
  description: "Generated by create next app",
};

<link
href="https://fonts.googleapis.com/css2?family=Oswald:wght@200;300;400;500;600;700&family=Urbanist:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap"
rel="stylesheet"
/>

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="h-[2000px]">
        <Header></Header>
        {children}
        <Footer></Footer>
        </body>
    </html>
  );
}
